---
abstract: 'Convert POD to ANSI-colored text'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Text-Ansi
no_index:
  directory:
    - t
    - utils
requires:
  Pod::Text: 3.13
  Term::ANSIColor: 0
  perl: 5.006
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Text-Ansi
  homepage: http://search.cpan.org/dist/Pod-Text-Ansi/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/pod-text-ansi.git
version: 0.05
x_authority: cpan:HINRIK
